version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    # Dependabot will add these labels to its PRs
    labels: ["type:deps", "bot"]
    # Optional: group small bumps to reduce PR noise
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["type:deps", "bot"]
