<<<<<<< HEAD
# areas labeled by path
=======
# area labels by path
area:sesame:
  - apps/core/portfolio/sesame.jiode.one/**

area:jiode.one:
  - apps/core/portfolio/jiode.one/**

area:genie-session:
  - apps/core/api/genie-session/**
>>>>>>> f4095271f0f4f8404b0356126de3e3e744f09078

type:ci:
  - .github/workflows/**
  - .github/actions/**

type:docs:
  - '**/*.md'
  - apps/**/README.md
<<<<<<< HEAD

type-deps:
  - changed-files:
      - any-glob-to-any-file: ["pnpm-lock.yaml", "**/package.json", ".github/workflows/**"]

scope-root:
  - changed-files:
      - any-glob-to-any-file: ["package.json", "pnpm-lock.yaml"]

scope-sesame:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/portfolio/sesame.jiode.one/**"

scope-jiode-one:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/portfolio/jiode.one/**"

scope-genie-session:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/api/genie-session/**"
=======
>>>>>>> f4095271f0f4f8404b0356126de3e3e744f09078
