# GitHub Labeler v5 config — use matcher objects (no bare strings)
# Labels are applied when ANY of the listed globs match changed files.

"type:ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"

"type:docs":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "apps/**/README.md"

"type:deps":
  - changed-files:
      - any-glob-to-any-file:
          - "pnpm-lock.yaml"
          - "**/package.json"
          - ".github/workflows/**"

"area:root":
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"

"area:sesame":
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/jiode/sesame.jiode.one/**"

"area:jiode.one":
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/jiode/jiode.one/**"

"area:genie-session":
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/api/genie-session/**"
