type:ci:
  - .github/workflows/**
  - .github/actions/**

type:docs:
  - '**/*.md'
  - apps/**/README.md

type-deps:
  - changed-files:
      - any-glob-to-any-file: ["pnpm-lock.yaml", "**/package.json", ".github/workflows/**"]

scope-root:
  - changed-files:
      - any-glob-to-any-file: ["package.json", "pnpm-lock.yaml"]

scope-sesame:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/portfolio/sesame.jiode.one/**"

scope-jiode-one:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/portfolio/jiode.one/**"

scope-genie-session:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/core/api/genie-session/**"

