// fieldMap.ts
export const FIELD_MAP = {
  id:               { type: 'string',          required: false, db: true,  zod: true, primary: true },
  title:            { type: 'string',          required: true,  db: true,  zod: true },
  slug:             { type: 'string',          required: true,  db: true,  zod: true, unique: true },
  slugPrefix:       { type: 'boolean',         required: false, db: false, zod: true },
  description:      { type: 'string',          required: false, db: false, zod: true },
  level:            { type: 'string',          required: false, db: true,  zod: true },
  audience:         { type: 'string',          required: false, db: true,  zod: true },
  created:          { type: 'string',          required: true,  db: true,  zod: true },
  edited:           { type: 'string',          required: false, db: true,  zod: true },
  excerpt:          { type: 'string',          required: true,  db: true,  zod: true },
  summaryPoints:    { type: 'string[]',        required: false, db: true,  zod: true, json: true },
  cover:            { type: 'string',          required: false, db: true,  zod: true },
  images:           { type: 'string[]',        required: false, db: false, zod: true },
  ogImageAlt:       { type: 'string',          required: false, db: true,  zod: true },
  languages:        { type: 'string',          required: false, db: true,  zod: true },
  author:           { type: 'string',          required: false, db: true,  zod: true },
  readingTime:      { type: 'number',          required: false, db: true,  zod: true },
  tags:             { type: 'string[]',        required: false, db: false, zod: true, joinTable: 'post_tags' },
  categories:       { type: 'string[]',        required: false, db: false, zod: true, joinTable: 'post_categories' },
  isSeries:         { type: 'boolean',         required: false, db: false, zod: true },
  series:           { type: 'string',          required: false, db: true,  zod: true },
  series_part:      { type: 'number',          required: false, db: true,  zod: true },
  draft:            { type: 'boolean',         required: false, db: true,  zod: true },
  featured:         { type: 'boolean',         required: false, db: true,  zod: true },
  dirty:            { type: 'boolean',         required: false, db: false, zod: true },
  published:        { type: 'boolean',         required: false, db: true,  zod: true },
  visibility:       { type: 'string',          required: false, db: true,  zod: true },
  status:           { type: 'string',          required: false, db: true,  zod: true },
  scheduled:        { type: 'string',          required: false, db: true,  zod: true },
  layout:           { type: 'string',          required: false, db: true,  zod: true },
  index:            { type: 'boolean',         required: false, db: true,  zod: true },
  comments:         { type: 'boolean',         required: false, db: true,  zod: true },
  redirectFrom:     { type: 'string[]',        required: false, db: true,  zod: true, json: true },
  contributors:     { type: 'string[]',        required: false, db: true,  zod: true, json: true },
  usedAI:           { type: 'boolean',         required: false, db: true,  zod: true },
  originalPrompt:   { type: 'string[]',        required: false, db: true,  zod: true, json: true },
  source:           { type: 'string',          required: false, db: true,  zod: true },
  canonical:        { type: 'string',          required: false, db: true,  zod: true },
  authRequired:     { type: 'boolean',         required: false, db: true,  zod: true },
  content:          { type: 'string',          required: false, db: true,  zod: false },
  metadata:         { type: 'record',          required: false, db: true,  zod: false },
};