# Only non-secret config here
SESAME_PRODUCTION_APP_ID: "sesame.jiode.one"
SESAME_PRODUCTION_PUBLIC_DIR: "apps/core/portfolio/sesame.jiode.one/public"
SESAME_PRODUCTION_WRANGLER_CONFIG: "apps/core/portfolio/sesame.jiode.one/sesame-meta-worker/wrangler.toml"
SESAME_PRODUCTION_R2_BUCKET: "sesame-data"
SESAME_PRODUCTION_HOST: "sesame.jiode.one"
