name = "resume-worker"
main = "resume-worker.js"
compatibility_date = "2025-06-11"

routes = [
  { pattern = "resume.fahrnbach.one", custom_domain = true }
]

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "RESUME_DATA"
bucket_name = "resume-data"
preview_bucket_name = "resume-data"
