name: Mark Deployment as Preview
description: Sets a preview environment for any deployment

inputs:
  wrangler_config:
    description: Optional Wrangler config file path
    required: false
  preview_host:
    description: The host for the preview environment
    required: false
    default: 'preview.jiode.one'


runs:
  using: composite
  steps:

    - name: Ensure code present
      uses: actions/checkout@v4

    - name: Create GitHub Deployment (preview)
      id: create
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const ref = context.payload.pull_request?.head?.ref || context.ref.replace('refs/heads/','');
          const res = await github.rest.repos.createDeployment({
            owner, repo,
            ref,
            environment: 'preview',          // must match branch protection
            auto_merge: false,
            required_contexts: [],           // don’t wait for other checks
            transient_environment: true,
            production_environment: false,
            description: 'PR preview (CI-only or real)'
          });
          core.setOutput('id', res.data.id);

    - name: Mark Deployment success
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const deployment_id = '${{ steps.create.outputs.id }}';
          await github.rest.repos.createDeploymentStatus({
            owner, repo,
            deployment_id,
            state: 'success',
            environment: 'preview',
            environment_url: 'https://${{ inputs.preview_host }}',
            log_url: `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`
          });
