name: Mark Deployment as Preview
description: Sets a preview environment for any deployment

inputs:
  wrangler_config:
    description: Optional Wrangler config file path
    required: false
  preview_host:
    description: The host for the preview environment
    required: false
    default: 'preview.jiode.one'


runs:
  using: composite
  steps:

    - name: Ensure code present
      uses: actions/checkout@v4

    - name: Create GitHub Deployment (preview)
      id: create
      uses: actions/github-script@v7
      with:
        script: |
          const res = await github.request('POST /repos/{owner}/{repo}/deployments', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,                // PR head SHA
            environment: 'preview',          // <-- must match your protected env name
            auto_merge: false,
            required_contexts: [],           // don’t block on status contexts
            transient_environment: true,
            production_environment: false,
            description: 'Sesame PR preview'
          });
          core.setOutput('id', res.data.id);
    - name: Mark Deployment success
      uses: actions/github-script@v7
      with:
        script: |
          const deployment_id = '${{ steps.create.outputs.id }}';
          await github.request('POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id,
            state: 'success',
            // If you have a stable preview URL, put it here:
            environment_url: 'https://${{ inputs.preview_host }}',
            log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
          });
