on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    if: ${{ !github.event.pull_request.merged }} || true # cleanup on any close
    runs-on: ubuntu-latest
    env:
      NAME: sesame-pr-${{ github.event.pull_request.number }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_PREVIEW }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PREVIEW }}
    steps:
      - name: Delete PR preview worker
        run: npx -y wrangler@4.33.0 delete "$NAME" || true
