name: Apply PR Labels by Path
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: labels-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
